version: '3'
services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data: # named volumes can be managed easier using docker-compose
